[tool.poetry]
name = "touschek"
version = "0.1.0"
description = ""
authors = ["Malte Titze <mtitze@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.8"
cpymad = "^1.8.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.5b1"
pylint = "^2.8.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
